### ISSUE TITLE
Add UART support to library

### ISSUE THREAD

**Issue by kattni** [adafruit/Adafruit_CircuitPython_AS726x#8]
This chip supports UART, however it was never implemented in the library. Please look into adding UART support for this board.

**Comment by caternuson** [comment]
@dherrada Want this one too? I have one of these, so can if you don't.

There's talk here:
https://github.com/adafruit/Adafruit_CircuitPython_BNO055/issues/41#issuecomment-548985618
of a taking the abstraction to another level. I think if that's going to happen, it might take some time to sort out. So suggest just doing the multiple subclass thing here for now. And also renaming them to remove the `Adafruit_` prefix. So:
```python
AS726x        # base class
AS726x_I2C    # I2C interface
AS726x_UART   # UART interface
```

**The above refactoring would be breaking changes** @kattni you OK with that?

**Comment by kattni** [comment]
@caternuson Apologies for the significant delay in response. If you're still interested in doing this, feel free. Breaking changes are fine. We'll do a full release bump and ensure we update any applicable guides.

**Comment by kattni** [comment]
This has been added.
